version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/cqrs/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/debug_page/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/enhanced_gradients/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/leancode_force_update"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/leancode_analytics/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/leancode_flutter_svg_adaptive_loader/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/leancode_hooks/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/leancode_lint/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/login_client/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/login_client_flutter/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/override_api_endpoint/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

  - package-ecosystem: "pub"
    directory: "/packages/leancode_markup/"
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    versioning-strategy: widen
