name: flutter_corelibrary

packages:
  - packages/*

scripts:
  get:
    run: melos exec flutter pub get

  analyze:
    run: melos exec flutter analyze

  test:
    run: melos exec flutter test
    packageFilters:
      dirExists:
        - test

  generate:
    run: melos exec -c 1 -- exec flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner

  clean:
    run: melos exec flutter clean
