name: debug_page
version: 1.0.0-alpha
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/debug_page
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  A package providing a debug page which shows outgoing http requests and Logger logs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  floating_chat_button: ^1.0.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  logging: ^1.2.0
  rxdart: ^0.27.7
  shake: ^2.2.0
  share_plus: ^7.0.2

dev_dependencies:
  custom_lint: ^0.5.6
  flutter_test:
    sdk: flutter
  leancode_lint: ^8.0.0
  mocktail: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
