name: leancode_debug_page
version: 1.0.1
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_debug_page
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  A package providing a debug page which shows outgoing http requests and Logger logs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  logging: ^1.2.0
  rxdart: ^0.27.7
  shake: ^2.2.0
  share_plus: ^9.0.0
  universal_io: ^2.2.2

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^12.1.0
  mocktail: ^1.0.3

flutter:
