name: leancode_debug_page
version: 2.1.2
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_debug_page
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  A package providing a debug page which shows outgoing http requests and Logger logs

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  logging: ^1.2.0
  rxdart: ^0.28.0
  sensors_plus: ^6.0.0
  share_plus: ^10.0.0

dev_dependencies:
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  leancode_lint: ^15.0.0
  mocktail: ^1.0.3

flutter:
