analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:leancode_lint/analysis_options.yaml

plugins:
  leancode_lint:
    path: ../..
