name: default_example
description: Example of using leancode_lint with the default configuration.
publish_to: none

environment:
  sdk: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint:
    path: ../..
