name: example
description: Example app for leancode_markup pacakge.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  leancode_markup:
    path: ..
  logging: ^1.2.0
  url_launcher: ^6.2.4

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^12.0.0

flutter:
  uses-material-design: true
  fonts:
    # "Delius Unicase" under SIL Open Font License from Google Fonts
    # https://fonts.google.com/specimen/Delius+Unicase
    - family: DeliusUnicase
      fonts:
        - asset: fonts/DeliusUnicase-Regular.ttf
        - asset: fonts/DeliusUnicase-Bold.ttf
          weight: 700
