name: cqrs_wrapper
version: 0.0.1
description: >-
  A library providing a convenient way of handling CQRS errors.

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cqrs: ^9.0.0
  http: ^1.0.0
  logging: ^1.2.0

dev_dependencies:
  coverage: ^1.5.0
  leancode_lint: ^4.0.0+1
  mocktail: ^0.3.0
  test: ^1.17.5
