name: leancode_analytics_firebase
description: Firebase Analytics implementation for LeanCode analytics.
version: 0.1.1
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_analytics_firebase
repository: https://github.com/leancodepl/flutter_corelibrary

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  firebase_analytics: ^12.2.0
  firebase_core: ^4.6.0
  flutter:
    sdk: flutter
  leancode_analytics_base: 0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^14.0.0

