name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cqrs: ^10.0.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.4.0
  leancode_force_update:
    path: ..
  logging: ^1.3.0
  mocktail: ^1.0.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^17.0.0

flutter:
  uses-material-design: true
