name: leancode_flutter_web_contract
description: Flutter web contract package by LeanCode.
version: 0.0.1
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_flutter_web_contract
repository: https://github.com/leancodepl/flutter_corelibrary

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  pub_semver: ^2.1.4
  web: ^1.1.0

dev_dependencies:
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  leancode_lint: ^18.0.0

flutter:
  assets:
    - assets/connect_to_host.js
