name: jaspr_class_scope_builder publish

on:
  push:
    tags: ['jaspr_class_scope_builder-v*']

jobs:
  publish:
    name: Publish to pub.dev

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    defaults:
      run:
        working-directory: packages/jaspr_class_scope_builder

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.13

      - name: Publish and release
        uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
        with:
          path: packages/jaspr_class_scope_builder
