name: leancode_analytics_posthog publish

on:
  push:
    tags: ['leancode_analytics_posthog-v*']

jobs:
  publish:
    name: Publish to pub.dev

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    defaults:
      run:
        working-directory: packages/leancode_analytics_posthog

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.x
          cache: true

      - name: Publish and release
        uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
        with:
          path: packages/leancode_analytics_posthog
