name: override_api_endpoint test

on:
  push:
    branches: [master]
    tags-ignore: ['override_api_endpoint-v*']
    paths:
      - 'packages/override_api_endpoint/**'
  pull_request:
    branches: [master]
    paths:
      - 'packages/override_api_endpoint/**'

jobs:
  test:
    name: Flutter ${{ matrix.channel }}${{ matrix.version }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '3.13.x'

    defaults:
      run:
        working-directory: packages/override_api_endpoint

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}
          flutter-version: ${{ matrix.version }}

      - name: Flutter version
        run: flutter --version

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Download pub dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Dry run pub publish
        # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
        run: dart pub publish --dry-run || true
